before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
    - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/julienbreux/exotic/cmd/exotic/main.version={{.Version}} -X github.com/julienbreux/exotic/cmd/exotic/main.commit={{.Commit}} -X github.com/julienbreux/exotic/cmd/exotic/main.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: clamp
    github:
      owner: JulienBreux
      name: homebrew-exotic
    commit_author:
      name: Julien Breux
      email: julien.breux@gmail.com
    folder: Formula
    homepage: https://julienbreux.github.io/exotic/
    description: Secret project
    test: system "exotic version --only"
