version = 1

[merge]
automerge_label = "workflow/automerge"
blacklist_labels = ["workflow/wip"]
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = true
notify_on_conflict = true
optimistic_updates = true

[merge.message]
title = "pull_request_title"
include_pr_number = true
body_type = "markdown"
