name: go

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - name: Download linter
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . latest
      - name: Lint
        run: ./golangci-lint run ./...
      - name: Test
        run: go test -v ./...
        env:
          GOPROXY: "https://proxy.golang.org"
      - name: Build
        run: 'go build -v -o ./exotic ./cmd/exotic'
        env:
          GOPROXY: "https://proxy.golang.org"
